### ISSUE TITLE
Downgrade addon

### ISSUE THREAD

**Issue by RedFoxy** [hassio-addons/addon-unifi#218]
I need to downgrade unifi controller, there is a way to do it without a snapshot, I need to go back to v0,21 with unifi controller 6.1.71

**Comment by frenck** [comment]
Home Assistant provides snapshots for that functionality. That is the only provided method.

**Comment by kvanla** [comment]
@frenck, So there is no way to get an older version without a snapshot? I am new to home assist and thus have no snapshot. Since ubiquit made my access points obsolute with this controller: https://community.ui.com/questions/Select-UniFi-Access-Point-AP-Models-Obsoletion-Date-March-1-2021/65487283-ce9d-49f4-85b9-b6aa54659ef7 , I need a controller with version 6.0.45.

**Comment by frenck** [comment]
Nope.

**Comment by RedFoxy** [comment]
I got an old home assistant snapshot from a friend with plugin version 0,19 and I fix it, than I moved the controller outside using docker
