### ISSUE TITLE
Unifi Controller No Statistics Data

### ISSUE THREAD

**Issue by FreakZAR** [hassio-addons/addon-unifi#226]
# Problem/Motivation

No Statistics Data in UI

## Expected behavior

Statistics Data visible in UI

## Actual behavior

No Statistics Data in UI

## Steps to reproduce

Seem to be on the  Controller Version 6.2.25 running on RPI 4
Core Version: core-2021.6.6
Supervisor Version: supervisor-2021.06.6

## Proposed changes

Known issue. Update Mongo binary as per https://www.reddit.com/r/UNIFI/comments/mg3fb2/no_statistic_data_since_controller_update/

**Comment by realthk** [comment]
Same here on amd64 (on which cannot apply the solution for Raspberry, so reverted back to v0.21 from April that still works fine)

**Comment by strasharo** [comment]
Same here on a RPI 4, when I try to open the statistics it's stuck on loading.

**Comment by frenck** [comment]
The latest release of the add-on (v1.0.0) uses a newer MongoDB version (which is now possible, since we have dropped 32-bits machine support). MongoDB 3.4.

This should in theory be enough according to UniFi specs, but I've not seen results as of yet. Further upgrades and changes from UniFi on this are expected for the 6.3 controller versions. And for the add-on, we can upgrade MongoDB to a newer version in a couple of months.
