### ISSUE TITLE
Addon stops randomly

### ISSUE THREAD

**Issue by KimCarlsen** [hassio-addons/addon-unifi#376]
The unify addon randomly stops, and doesn't start, even that it has watchdog enabled. i can then manually start it without any problems.
All settings are default, (except log_level: debug)

But there are no traces of why it stops in the logs, so how do i troubleshoot?
It is the only addon that behaves like this.

Using HA version: 2022.6.8 
HA OS: 8.4
Unifi addon version: 2.3.1
But seem with previous versions as well

**Comment by frenck** [comment]
> The unify addon randomly stops
> i can then manually start it without any problems.
> But there are no traces of why it stops in the logs

To me, this sounds like out-of-memory issues (causing the OOM killer to take a stab). This should be visible in the OS logs.

> and doesn't start, even that it has watchdog enabled. 

That is outside of control from the add-on, and should be reported with the Home Assistant Supervisor project.

**Comment by KimCarlsen** [comment]
thanks. i'll keep an eye on it and gather the logs

**Comment by Naesstrom** [comment]
I've been having problems lately with my hass install (Pi4/4Gb) getting unresponsive because of completely out of memory. Tonight I saw that the unifi addon was using 25% RAM so shut it down. Thinking it might be related to this issue?
Addon 2.3.1
Home Assistant 2022.9.2
Supervisor 2022.08.6
Operating System 8.5
Frontend 20220907.0 - latest
![image](https://user-images.githubusercontent.com/6575206/189990024-dffaec21-cd05-4f88-a59d-bf93c4ac0652.png)
