### ISSUE TITLE
NO web ui visible

### ISSUE THREAD

**Issue by KingMark66** [hassio-addons/addon-unifi#487]
# Problem/Motivation
When I followed the installation guide and open the web ui. It opens a new tab. But fails after 30sec. I wanted to configure my 2 unifi access points. They are now configured with my laptop, but he isn't always on
> (Why the issue was filed)

## Expected behavior
Web ui that opens
> (What you expected to happen)

## Actual behavior
Web uit that doesn't open
> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by renewoensdregt** [comment]
I think you better report this on the Home assistant community with some more information. I feel this is not a bug but more incorrect configuration. The info provided is not enough to help you.
________________________________
From: Mark Vroman ***@***.***>
Sent: Tuesday, February 6, 2024 2:23 PM
To: hassio-addons/addon-unifi ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hassio-addons/addon-unifi] NO web ui visible (Issue #487)


Problem/Motivation

When I followed the installation guide and open the web ui. It opens a new tab. But fails after 30sec. I wanted to configure my 2 unifi access points. They are now configured with my laptop, but he isn't always on

(Why the issue was filed)

Expected behavior

Web ui that opens

(What you expected to happen)

Actual behavior

Web uit that doesn't open

(What actually happened)

Steps to reproduce

(How can someone else make/see it happen)

Proposed changes

(If you have a proposed change, workaround or fix,
describe the rationale behind it)
