### ISSUE TITLE
Update to UniFi Network Application 8.1.113

### ISSUE THREAD

**Issue by dobrac** [hassio-addons/addon-unifi#494]
# Problem/Motivation

Hi, thank you for your work on this add-on. 

A new version of UniFi Network Application 8.1.113 was released a week ago:
https://community.ui.com/releases/UniFi-Network-Application-8-1-113/af46fd38-8afe-4cef-8de1-89636b02b52c

Is there any plan to update this add-on too in the near future? I would love to have the update as it contains a lot of improvements.

## Expected behavior

Update to version 8.1.113

## Actual behavior

No update yet

## Steps to reproduce

---

## Proposed changes

Update to version 8.1.113

**Comment by renewoensdregt** [comment]
It was just added today to the formal list : https://www.ui.com/download/releases/network-server.

Feel free to make a pull request or just wait until someone else does. I might do soon, but don’t have too much time at the moment. Will see if I have time inbetween.
________________________________
From: Jakub Dobry ***@***.***>
Sent: Wednesday, March 20, 2024 11:27:24 AM
To: hassio-addons/addon-unifi ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hassio-addons/addon-unifi] Update to UniFi Network Application 8.1.113 (Issue #494)


Problem/Motivation

Hi, thank you for your work on this add-on.

A new version of UniFi Network Application 8.1.113 was released a week ago:
https://community.ui.com/releases/UniFi-Network-Application-8-1-113/af46fd38-8afe-4cef-8de1-89636b02b52c

Is there any plan to update this add-on too in the near future? I would love to have the update as it contains a lot of improvements.

Expected behavior

Update to version 8.1.113

Actual behavior

No update yet

Steps to reproduce
________________________________
Proposed changes

Update to version 8.1.113

**Comment by frenck** [comment]
Closing this one, as this is not an issue, but an request.

Feel free to contribute 👍 

../Frenck
