### ISSUE TITLE
webgui unavailable

### ISSUE THREAD

**Issue by skank01** [hassio-addons/addon-unifi#70]
I had a HA crash, so had to restore from a backup
The unifi addon is installed good from the backup

Normally i can reach the webgui, but now i cant
i get a 
connection refused warning

Log from addon says:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: UniFi Controller
 Manage your UniFi network using a web browser
-----------------------------------------------------------
 Add-on version: 0.14.0
 You are running the latest version of this add-on.
 System: HassOS 3.12  (armv7 / raspberrypi4)
 Home Assistant Core: 0.107.4
 Home Assistant Supervisor: 209
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] unifi.sh: executing... 
[cont-init.d] unifi.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:47:22] INFO: Starting the UniFi Controller...

not sure whats wrong, restarting doesnt help

**Comment by EmnaX** [comment]
I'm running into similar issues. I had a Pi with an older installation of Home Assistant (HA) on it. I think it was 0.100. I had installed the UniFi controller (from Ubiquiti), directly on the OS (as in not a docker image). I made a backup of the UniFi controller and my HA config and started with a fresh installation of Home Assistant. I installed the UniFi controller through the add-on this time because with the latest versions of Home Assistant, I didn't have access to the underlying OS any longer. The UniFi add-on loads up fine but when I load my backup, the UniFi controller seems to get stuck at "Starting..." I'm not sure where else to look for logs other than what is shown in the add-on logs (see below).

Moving forward, I'll setup the controller as a new one and re-import my Ubiquiti devices. Bit of a pain but hopefully that will get everything up and running again!

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
/-----------------------------------------------------------
 Hass.io Add-on: UniFi Controller
 Manage your UniFi network using a web browser
/-----------------------------------------------------------
 Add-on version: 0.14.0
 You are running the latest version of this add-on.
 System: HassOS 3.12  (armv7 / raspberrypi3)
 Home Assistant Core: 0.107.5
 Home Assistant Supervisor: 209
/-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
/-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] unifi.sh: executing... 
[cont-init.d] unifi.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[08:36:16] INFO: Starting the UniFi Controller...

**Comment by snizzleorg** [comment]
Same problem here no errors in the log but no GUI
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: UniFi Controller
 Manage your UniFi network using a web browser
-----------------------------------------------------------
 Add-on version: 0.14.0
 You are running the latest version of this add-on.
 System: HassOS 3.12  (armv7 / raspberrypi3)
 Home Assistant Core: 0.107.4
 Home Assistant Supervisor: 209
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] unifi.sh: executing... 
[cont-init.d] unifi.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:41:58] INFO: Starting the UniFi Controller...`

**Comment by apop880** [comment]
Same issue for me since upgrading from 0.14.0 to 0.14.1

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: UniFi Controller
 Manage your UniFi network using a web browser
-----------------------------------------------------------
 Add-on version: 0.14.1
 There is an update available for this add-on!
 Latest add-on version: null
 Please consider upgrading as soon as possible.
 System: HassOS 3.12  (armv7 / raspberrypi3)
 Home Assistant Core: 0.106.5
 Home Assistant Supervisor: 214
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
```

**Comment by snizzleorg** [comment]
Any news on this? I still am not able to get this component working.

**Comment by Koudy2410** [comment]
Same problem.

**Comment by mysliwiec-tech** [comment]
Also see the same problem. Hangs on `Starting the UniFi Controller...`

**Comment by TheGhost2804** [comment]
Same problem

**Comment by jefersonkennedy** [comment]
Same problem

**Comment by josephkiser04** [comment]
Same problem. Any updates?

**Comment by mysliwiec-tech** [comment]
Seems like the updated version works for me fine.

**Comment by sinclairpaul** [comment]
`INFO: Starting the UniFi Controller...`

This is the expected message from the logs once the controller is started.

Some things to check:

The UI runs on port 8443, what DNS name are you accessing it on?
Is this resolved to an internal address, or does your external router support hairpin/loopback NAT?
What happens when you access https://myserveripaddress:8443 (for example https://192.168.1.1:8443)

Unfortunately there is nothing in the logged issues to look at, if someone could post the output from a browser dev console it may be helpful.

**Comment by httpedo13** [comment]
now I have solved by stopping and restarting both the unifi addon and duckdns.  however I saw that after a while the problem returns and I will try to send a screenshot

**Comment by httpedo13** [comment]
![Screenshot_20200723-000416~2](https://user-images.githubusercontent.com/40502451/88233536-2f4def80-cc78-11ea-83eb-7ccca352dd48.png)

**Comment by sinclairpaul** [comment]
I would guess that you access via your duckdns domain and your connection is resolving externally and therefore being blocked as the port is closed.

What happens when you access via the local IP?
What do the browser dev tools say (F12, Network Tab) mobile likely won't help you here?
What does the address resolve to?

This really looks like a name resolution issue.

**Comment by httpedo13** [comment]
> I would guess that you access via your duckdns domain and your connection is resolving externally and therefore being blocked as the port is closed.
> 
> What happens when you access via the local IP?
> What do the browser dev tools say (F12, Network Tab) mobile likely won't help you here?
> What does the address resolve to?
> 
> This really looks like a name resolution issue.

<img width="1440" alt="Schermata 2020-07-23 alle 18 31 24" src="https://user-images.githubusercontent.com/40502451/88312798-e008cd00-cd12-11ea-8ab8-6183c25ba437.png">

this is with https://IP:8443 but is the same with external domain like https://xxx.duckdns.org:8443

**Comment by sinclairpaul** [comment]
Please retry after clearing the browser cache (or disabling it with the dev tools), and post the full dev tools console output.

**Comment by ivan-novakov** [comment]
It happens to me on every restart of HA. According to the CPU and memory usage it seems that it has started, but for some reason probably got stuck somewhere on the way.
What usually helps is to restart it 1-2 times and then I can access the controller.
I use the local IP address.

**Comment by claesr** [comment]
I have never had any issues with the controller before and always used it locally only, but suddenly I get "Error connecting to the UniFi controller at 192.168...." in the home assistant log file while the Controller log says "[10:56:27] INFO: Starting the UniFi Controller..." and then nothing happens.

Add-on version: 0.18.1 - You are running the latest version of this add-on.
System: HassOS 4.12  (armv7 / raspberrypi3)
Home Assistant Core: 0.114.4
Home Assistant Supervisor: 235

Any ideas? I tried to reboot the host as well.

**Comment by BartEngelen** [comment]
Same issue here. Restart HA several times no solution, restart the add-on several times no solution.
