### ISSUE TITLE
Wouldn't adopt. Error in log. Uninstalled.

### ISSUE THREAD

**Issue by boomalator** [hassio-addons/addon-unifi#97]
# Problem/Motivation

Products should work. Errors should not occur.

## Expected behavior

The add-on to act like all the other UniFi controllers, adopt and manage APs. Start without error.

## Actual behavior

Tried to adopt factory-reset AP. Stayed in "Adopting" for hours. In addition, add-on log shows errors. As well, "Open Web UI" does not function for several minutes. (Says connection refused.) 

On top of that, something was setting the inform URL to 172.30.33.3 -- which I gather has something to do with docker/containers -- but is not a reachable address on my network (outside of docker on HA, at least). When I set the inform in the AP (via SSH) to the host name or LAN-side IP of HA server, the info command says "server rejected" the adoption request.

## Steps to reproduce

Install addon. Attempt to use.

## Proposed changes

I will continue to use my regular UniFi controller, hosted outside of HA.

I sorry, I thought I captured the log before uninstalling, but I guess I didn't. The error was a Java error about a string out of bounds.

**Comment by davethayer** [comment]
I had a similar problem including the same IP address. 

It turns out that I had neglected to change the "Controller Hostname/IP" entry and check the "Override inform host with controller hostname/IP" box in the "Controller Settings" section of the "Controller" tab on the Setup page.

For a step-by-step procedure see items 6-9 in the HA add-on installation instuctions.

**Comment by jrc** [comment]
That works. Related #79 

This issue should be closed.
